[package]
name = "giki"
version = "0.1.0"
edition = "2021"
authors = ["Luna Borella <ulfrthewolf@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.15"
